version: "3.8"

services:
  gpl-virtual-stand:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpl-virtual-stand
    ports:
      - "8000:8000"
    restart: unless-stopped
