version: "3.8"

services:
  gpl-virtual-stand:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpl-virtual-stand
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
